nameserver /activity-wbsj.com/yys
nameserver /aihst8.com/yys
nameserver /amemv.cn/yys
nameserver /amemv.com/yys
nameserver /amemv.net/yys
nameserver /awemeughun.com/yys
nameserver /awemeuglang.com/yys
nameserver /awemeugsoul.com/yys
nameserver /awemeugwave.com/yys
nameserver /betastar.cn/yys
nameserver /boxdouyin.com/yys
nameserver /bytednsdoc.com/yys
nameserver /cookicut.com/yys
nameserver /douyin.com/yys
nameserver /douyinact.com/yys
nameserver /douyinact.net/yys
nameserver /douyincdn.com/yys
nameserver /douyinfe.com/yys
nameserver /douyinliving.com/yys
nameserver /douyinpic.com/yys
nameserver /douyinstatic.com/yys
nameserver /douyinvod.com/yys
nameserver /duoshan.com/yys
nameserver /huoshan.com/yys
nameserver /huoshancdn.com/yys
nameserver /huoshangroup.com/yys
nameserver /huoshanimg.com/yys
nameserver /huoshanlive.com/yys
nameserver /huoshanparty.com/yys
nameserver /huoshanstatic.com/yys
nameserver /huoshante8.com/yys
nameserver /huoshanvideo.cn/yys
nameserver /huoshanvideo.net/yys
nameserver /huoshanvod.com/yys
nameserver /huoshanxiaoshipin.cn/yys
nameserver /huoshanxiaoshipin.net/yys
nameserver /huoshanzhibo.cn/yys
nameserver /huoshanzhibo.com/yys
nameserver /huoshanzhibo.net/yys
nameserver /idouyinliving.com/yys
nameserver /idouyinpic.com/yys
nameserver /idouyinstatic.com/yys
nameserver /idouyinvod.com/yys
nameserver /iesdouyin.com/yys
nameserver /iesdouyin.net/yys
nameserver /ieshuodong.cn/yys
nameserver /ieshuodong.net/yys
nameserver /ihst8.com/yys
nameserver /ihuoshanimg.com/yys
nameserver /ihuoshanlive.com/yys
nameserver /ihuoshanstatic.com/yys
nameserver /ihuoshanvod.com/yys
nameserver /ixigua.com/yys
nameserver /ixiguavideo.com/yys
nameserver /kesong.co/yys
nameserver /kolbuyer.cn/yys
nameserver /nextvid.net/yys
nameserver /ppkankan01.com/yys
nameserver /pstatp.com/yys
nameserver /qishui.cn/yys
nameserver /qishui.com/yys
nameserver /qishui.com.cn/yys
nameserver /qishuimusic.cn/yys
nameserver /qishuimusic.com.cn/yys
nameserver /snssdk.com/yys
nameserver /supercachenet.com/yys
nameserver /supercachenode.com/yys
nameserver /toutiao.com/yys
nameserver /ultracachenode.com/yys
nameserver /woaihuoshan.com/yys
nameserver /wohst8.com/yys
nameserver /zjcdn.com/yys
