# 将 z 和 x 的增减步长修改为 0.5 秒（即 500ms）
z add sub-delay -0.5
x add sub-delay +0.5

[ add speed -0.25
] add speed +0.25

RIGHT no-osd seek +3
LEFT  no-osd seek -3

MBTN_LEFT cycle pause
MBTN_LEFT_DBL ignore
